### ISSUE TITLE
Please remove the specific commit.

### ISSUE THREAD

**Issue by Stereoarts** [bgoonz/UsefulResourceRepo2.0#32]
Hi,

Can I ask you to remove this commit?
https://github.com/bgoonz/UsefulResourceRepo2.0/commit/5927cb5255936b379b29faf6df565f593d84962a

This commit contains this directory.
UsefulResourceRepo2.0/_REPO/GITHUB/dmca/

So this directory contains too many garbages & make dirty on search results all over.

**Comment by bgoonz** [comment]
@Stereoarts Done
